name: mbtfe
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.23,<2.0
  # ---- PyTorch stack pinned to the last PYG-supported major (2.1.*) ----
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  # ---- CUDA runtime that matches this PyTorch build ----
  - pytorch-cuda=11.8
  # ---- PyTorch Geometric meta-package (conda) ----
  - pyg=2.4.0
  # ---- Common scientific stack ----
  - matplotlib
  - pandas
  - pip
